In [2]:
import torch

print(torch.__version__)

2.4.0+cpu


In [5]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.Tensor([1, 2, 3]) # 권장
tensor3 = torch.LongTensor([1, 2, 3]) # 64-integer
tensor4 = torch.FloatTensor([1, 2, 3])

for i in range(1, 5):
    tensor = locals()["tensor{}".format(i)]
    print(tensor)

tensor([1, 2, 3])
tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1., 2., 3.])


In [6]:
tensor = torch.rand(1, 2)
print(tensor)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

tensor([[0.2346, 0.3656]])
torch.Size([1, 2])
torch.float32
cpu


In [7]:
tensor = tensor.reshape(2, 1)
print(tensor)
print(tensor.shape)

tensor([[0.2346],
        [0.3656]])
torch.Size([2, 1])


In [12]:
tensor = tensor.reshape(-1, 1, 1)
print(tensor)

tensor([[[0.2346]],

        [[0.3656]]])


In [13]:
tensor = torch.rand((3, 3), dtype=torch.float)
print(tensor)

tensor([[0.5021, 0.5398, 0.1277],
        [0.2128, 0.6778, 0.9236],
        [0.6725, 0.1667, 0.8971]])


In [14]:
cpu = torch.FloatTensor([1, 2, 3])
gpu = cpu.cuda()
gpu2cpu = gpu.cpu()
cpu2gpu = cpu.to("cuda")
print(cpu)
print(gpu)
print(gpu2cpu)
print(cpu2gpu)

AssertionError: Torch not compiled with CUDA enabled

In [15]:
import numpy as np

ndarray = np.array([1, 2, 3], dtype=np.uint8)
print(torch.tensor(ndarray))
print(torch.Tensor(ndarray))
print(torch.from_numpy(ndarray))

tensor([1, 2, 3], dtype=torch.uint8)
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.uint8)


In [16]:
tensor = torch.FloatTensor([1, 2, 3])
ndarray = tensor.detach().numpy()
print(ndarray)
print(type(ndarray))

[1. 2. 3.]
<class 'numpy.ndarray'>


<h5>단순 선형회귀(numpy, torch, torch.nn(신경망) 사용)</h5>

In [18]:
import numpy as np

x = np.array(
    [[1], [2], [3], [4], [5], [6], [7], [8], [9], [10],
    [11], [12], [13], [14], [15], [16], [17], [18], [19], [20],
    [21], [22], [23], [24], [25], [26], [27], [28], [29], [30]]
)
y = np.array(
    [[0.94], [1.98], [2.88], [3.92], [3.96], [4.55], [5.64], [6.3], [7.44], [9.1],
    [8.46], [9.5], [10.67], [11.16], [14], [11.83], [14.4], [14.25], [16.2], [16.32],
    [17.46], [19.8], [18], [21.34], [22], [22.5], [24.57], [26.04], [21.6], [28.8]]
)

In [23]:
def test_loss(learning_rate_):
    x = np.array(
    [[1], [2], [3], [4], [5], [6], [7], [8], [9], [10],
    [11], [12], [13], [14], [15], [16], [17], [18], [19], [20],
    [21], [22], [23], [24], [25], [26], [27], [28], [29], [30]]
    )
    y = np.array(
        [[0.94], [1.98], [2.88], [3.92], [3.96], [4.55], [5.64], [6.3], [7.44], [9.1],
        [8.46], [9.5], [10.67], [11.16], [14], [11.83], [14.4], [14.25], [16.2], [16.32],
        [17.46], [19.8], [18], [21.34], [22], [22.5], [24.57], [26.04], [21.6], [28.8]]
    )
    weight = 0.0
    bias = 0.0
    for epoch in range(10000):
        y_hat = weight * x + bias
        cost = ((y - y_hat) ** 2).mean()
        
        weight = weight - learning_rate_ * ((y_hat - y) * x).mean()
        bias = bias - learning_rate_ * (y_hat - y).mean()
        
        if (epoch + 1) % 1000 == 0:
            print(f"Epoch : {epoch+1:4d}, Weight : {weight:.3f}, Bias : {bias:.3f}, Cost : {cost:.3f}")

In [24]:
test_loss(0.001) # cost값이 상대적으로 천천히 감소

Epoch : 1000, Weight : 0.860, Bias : -0.059, Cost : 1.406
Epoch : 2000, Weight : 0.864, Bias : -0.138, Cost : 1.393
Epoch : 3000, Weight : 0.867, Bias : -0.201, Cost : 1.385
Epoch : 4000, Weight : 0.870, Bias : -0.251, Cost : 1.380
Epoch : 5000, Weight : 0.872, Bias : -0.290, Cost : 1.377
Epoch : 6000, Weight : 0.873, Bias : -0.321, Cost : 1.375
Epoch : 7000, Weight : 0.874, Bias : -0.345, Cost : 1.374
Epoch : 8000, Weight : 0.875, Bias : -0.364, Cost : 1.373
Epoch : 9000, Weight : 0.876, Bias : -0.379, Cost : 1.373
Epoch : 10000, Weight : 0.877, Bias : -0.391, Cost : 1.373


In [26]:
test_loss(0.001)

Epoch : 1000, Weight : 0.860, Bias : -0.059, Cost : 1.406
Epoch : 2000, Weight : 0.864, Bias : -0.138, Cost : 1.393
Epoch : 3000, Weight : 0.867, Bias : -0.201, Cost : 1.385
Epoch : 4000, Weight : 0.870, Bias : -0.251, Cost : 1.380
Epoch : 5000, Weight : 0.872, Bias : -0.290, Cost : 1.377
Epoch : 6000, Weight : 0.873, Bias : -0.321, Cost : 1.375
Epoch : 7000, Weight : 0.874, Bias : -0.345, Cost : 1.374
Epoch : 8000, Weight : 0.875, Bias : -0.364, Cost : 1.373
Epoch : 9000, Weight : 0.876, Bias : -0.379, Cost : 1.373
Epoch : 10000, Weight : 0.877, Bias : -0.391, Cost : 1.373


In [27]:
test_loss(0.006)

Epoch : 1000, Weight : 0.873, Bias : -0.321, Cost : 1.375
Epoch : 2000, Weight : 0.878, Bias : -0.408, Cost : 1.372
Epoch : 3000, Weight : 0.879, Bias : -0.429, Cost : 1.372
Epoch : 4000, Weight : 0.879, Bias : -0.434, Cost : 1.372
Epoch : 5000, Weight : 0.879, Bias : -0.436, Cost : 1.372
Epoch : 6000, Weight : 0.879, Bias : -0.436, Cost : 1.372
Epoch : 7000, Weight : 0.879, Bias : -0.436, Cost : 1.372
Epoch : 8000, Weight : 0.879, Bias : -0.436, Cost : 1.372
Epoch : 9000, Weight : 0.879, Bias : -0.436, Cost : 1.372
Epoch : 10000, Weight : 0.879, Bias : -0.436, Cost : 1.372


In [30]:

import numpy as np

x = np.array(
    [[1], [2], [3], [4], [5], [6], [7], [8], [9], [10],
    [11], [12], [13], [14], [15], [16], [17], [18], [19], [20],
    [21], [22], [23], [24], [25], [26], [27], [28], [29], [30]]
)
y = np.array(
    [[0.94], [1.98], [2.88], [3.92], [3.96], [4.55], [5.64], [6.3], [7.44], [9.1],
    [8.46], [9.5], [10.67], [11.16], [14], [11.83], [14.4], [14.25], [16.2], [16.32],
    [17.46], [19.8], [18], [21.34], [22], [22.5], [24.57], [26.04], [21.6], [28.8]]
)
weight = 0.0
bias = 0.0
learning_rate = 0.006
for epoch in range(10000):
    y_hat = weight * x + bias

    cost = ((y - y_hat) ** 2).mean()

    weight = weight - learning_rate * ((y_hat - y) * x).mean()
    bias = bias - learning_rate * (y_hat - y).mean()

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Weight : {weight:.3f}, Bias : {bias:.3f}, Cost : {cost:.3f}")

Epoch : 1000, Weight : 0.873, Bias : -0.321, Cost : 1.375
Epoch : 2000, Weight : 0.878, Bias : -0.408, Cost : 1.372
Epoch : 3000, Weight : 0.879, Bias : -0.429, Cost : 1.372
Epoch : 4000, Weight : 0.879, Bias : -0.434, Cost : 1.372
Epoch : 5000, Weight : 0.879, Bias : -0.436, Cost : 1.372
Epoch : 6000, Weight : 0.879, Bias : -0.436, Cost : 1.372
Epoch : 7000, Weight : 0.879, Bias : -0.436, Cost : 1.372
Epoch : 8000, Weight : 0.879, Bias : -0.436, Cost : 1.372
Epoch : 9000, Weight : 0.879, Bias : -0.436, Cost : 1.372
Epoch : 10000, Weight : 0.879, Bias : -0.436, Cost : 1.372


In [45]:
import torch
from torch import optim 

In [46]:
x = torch.FloatTensor([
    [1], [2], [3], [4], [5], [6], [7], [8], [9], [10],
    [11], [12], [13], [14], [15], [16], [17], [18], [19], [20],
    [21], [22], [23], [24], [25], [26], [27], [28], [29], [30]
])
y = torch.FloatTensor([
    [0.94], [1.98], [2.88], [3.92], [3.96], [4.55], [5.64], [6.3], [7.44], [9.1],
    [8.46], [9.5], [10.67], [11.16], [14], [11.83], [14.4], [14.25], [16.2], [16.32],
    [17.46], [19.8], [18], [21.34], [22], [22.5], [24.57], [26.04], [21.6], [28.8]
])

In [47]:
weight = torch.zeros(1, requires_grad=True)
bias = torch.zeros(1, requires_grad=True)
learning_rate = 0.001

In [38]:
weight

tensor([0.], requires_grad=True)

In [48]:
optimizer = optim.SGD([weight, bias], lr=learning_rate)

In [42]:
for epoch in range(10000):
    hypothesis = x * weight + bias # 가설(연구가설, 대립가설) 설정
    cost = torch.mean((hypothesis - y) ** 2)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Weight : {weight.item():.3f}, Bias : {bias.item():.3f}, Cost : {cost:.3f}")

Epoch : 1000, Weight : 0.864, Bias : -0.139, Cost : 1.393
Epoch : 2000, Weight : 0.870, Bias : -0.251, Cost : 1.380
Epoch : 3000, Weight : 0.873, Bias : -0.321, Cost : 1.375
Epoch : 4000, Weight : 0.875, Bias : -0.364, Cost : 1.373
Epoch : 5000, Weight : 0.877, Bias : -0.391, Cost : 1.373
Epoch : 6000, Weight : 0.878, Bias : -0.408, Cost : 1.372
Epoch : 7000, Weight : 0.878, Bias : -0.419, Cost : 1.372
Epoch : 8000, Weight : 0.878, Bias : -0.425, Cost : 1.372
Epoch : 9000, Weight : 0.879, Bias : -0.429, Cost : 1.372
Epoch : 10000, Weight : 0.879, Bias : -0.432, Cost : 1.372


In [50]:
for epoch in range(10000):
    hypothesis = x * weight + bias # 가설(연구가설, 대립가설) 설정
    cost = torch.mean((hypothesis - y) ** 2)
    
    print(f"Epoch: {epoch+1:4d}")
    print(f"Step [1] : Gradient : {weight.grad}, Weight : {weight.item():.5f}")
    
    optimizer.zero_grad() # 이전 epoch에서 계산한 기울기 초기화 -- gradient = x 형식이 아닌 gradient += x 형식으로 저장되기 때문 이유는 모름
    print(f"Step [2] : Gradient : {weight.grad}, Weight : {weight.item():.5f}")
    
    cost.backward()
    print(f"Step [3] : Gradient : {weight.grad}, Weight : {weight.item():.5f}")
    
    optimizer.step()
    print(f"Step [4] : Gradient : {weight.grad}, Weight : {weight.item():.5f}")

Epoch:    1
Step [1] : Gradient : None, Weight : 0.00000
Step [2] : Gradient : None, Weight : 0.00000
Step [3] : Gradient : tensor([-540.4854]), Weight : 0.00000
Step [4] : Gradient : tensor([-540.4854]), Weight : 0.54049
Epoch:    2
Step [1] : Gradient : tensor([-540.4854]), Weight : 0.54049
Step [2] : Gradient : None, Weight : 0.54049
Step [3] : Gradient : tensor([-198.9818]), Weight : 0.54049
Step [4] : Gradient : tensor([-198.9818]), Weight : 0.73947
Epoch:    3
Step [1] : Gradient : tensor([-198.9818]), Weight : 0.73947
Step [2] : Gradient : None, Weight : 0.73947
Step [3] : Gradient : tensor([-73.2604]), Weight : 0.73947
Step [4] : Gradient : tensor([-73.2604]), Weight : 0.81273
Epoch:    4
Step [1] : Gradient : tensor([-73.2604]), Weight : 0.81273
Step [2] : Gradient : None, Weight : 0.81273
Step [3] : Gradient : tensor([-26.9772]), Weight : 0.81273
Step [4] : Gradient : tensor([-26.9772]), Weight : 0.83970
Epoch:    5
Step [1] : Gradient : tensor([-26.9772]), Weight : 0.83970
S

In [51]:
from torch import nn 

model = nn.Linear(1, 1, bias=True)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [53]:
for epoch in range(10000):
    output = model(x)
    cost = criterion(output, y)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch + 1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[0.8472]], requires_grad=True), Parameter containing:
tensor([-0.9768], requires_grad=True)], Cost : 2.514
Epoch : 2000, Model : [Parameter containing:
tensor([[0.8472]], requires_grad=True), Parameter containing:
tensor([-0.9768], requires_grad=True)], Cost : 2.514
Epoch : 3000, Model : [Parameter containing:
tensor([[0.8472]], requires_grad=True), Parameter containing:
tensor([-0.9768], requires_grad=True)], Cost : 2.514
Epoch : 4000, Model : [Parameter containing:
tensor([[0.8472]], requires_grad=True), Parameter containing:
tensor([-0.9768], requires_grad=True)], Cost : 2.514
Epoch : 5000, Model : [Parameter containing:
tensor([[0.8472]], requires_grad=True), Parameter containing:
tensor([-0.9768], requires_grad=True)], Cost : 2.514
Epoch : 6000, Model : [Parameter containing:
tensor([[0.8472]], requires_grad=True), Parameter containing:
tensor([-0.9768], requires_grad=True)], Cost : 2.514
Epoch : 7000, Model : [Parameter contain

<h4 style="color:red">poly LinearRegressor</h4>

In [54]:
import torch
from torch import nn
from torch import optim
from torch.utils.data import TensorDataset, DataLoader 

train_x = torch.FloatTensor([
    [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7]
])
train_y = torch.FloatTensor([
    [0.1, 1.5], [1, 2.8], [1.9, 4.1], [2.8, 5.4], [3.7, 6.7], [4.6, 8]
])

In [55]:
train_dataset = TensorDataset(train_x, train_y)
train_dataloader = DataLoader(train_dataset, batch_size=2, shuffle=True, drop_last=True)

In [56]:
model = nn.Linear(2, 2, bias=True)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [58]:
for epoch in range(10000):
    cost = 0.0
    
    for batch in train_dataloader:
        x, y = batch 
        output = model(x)
        
        loss = criterion(output, y)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        cost += loss # batch를 쪼개서 학습하기 때문에 1epoch당 cost값을 계산하기 위해 cost += 방식을 사용
        
    cost = cost / len(train_dataloader) # loss 평군값 계산
    
    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch + 1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[ 1.0566, -0.2213],
        [ 0.6960,  0.5595]], requires_grad=True), Parameter containing:
tensor([-0.3061, -0.1720], requires_grad=True)], Cost : 0.011
Epoch : 2000, Model : [Parameter containing:
tensor([[ 1.1223, -0.2553],
        [ 0.7412,  0.5361]], requires_grad=True), Parameter containing:
tensor([-0.4058, -0.2406], requires_grad=True)], Cost : 0.003
Epoch : 3000, Model : [Parameter containing:
tensor([[ 1.1558, -0.2726],
        [ 0.7642,  0.5242]], requires_grad=True), Parameter containing:
tensor([-0.4566, -0.2755], requires_grad=True)], Cost : 0.001
Epoch : 4000, Model : [Parameter containing:
tensor([[ 1.1729, -0.2815],
        [ 0.7760,  0.5181]], requires_grad=True), Parameter containing:
tensor([-0.4825, -0.2934], requires_grad=True)], Cost : 0.000
Epoch : 5000, Model : [Parameter containing:
tensor([[ 1.1816, -0.2859],
        [ 0.7819,  0.5151]], requires_grad=True), Parameter containing:
tensor([-0.4957, -0.3024], 

In [59]:
model = nn.Linear(2, 2, bias=False) # bias를 사용 안하고 실험
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

for epoch in range(10000):
    cost = 0.0
    
    for batch in train_dataloader:
        x, y = batch 
        output = model(x)
        
        loss = criterion(output, y)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        cost += loss # batch를 쪼개서 학습하기 때문에 1epoch당 cost값을 계산하기 위해 cost += 방식을 사용
        
    cost = cost / len(train_dataloader) # loss 평군값 계산
    
    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch + 1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[0.5788, 0.1066],
        [0.5023, 0.6833]], requires_grad=True)], Cost : 0.104
Epoch : 2000, Model : [Parameter containing:
tensor([[ 0.8090, -0.0794],
        [ 0.6250,  0.5841]], requires_grad=True)], Cost : 0.065
Epoch : 3000, Model : [Parameter containing:
tensor([[ 0.9918, -0.2274],
        [ 0.7225,  0.5053]], requires_grad=True)], Cost : 0.041
Epoch : 4000, Model : [Parameter containing:
tensor([[ 1.1372, -0.3448],
        [ 0.8000,  0.4426]], requires_grad=True)], Cost : 0.026
Epoch : 5000, Model : [Parameter containing:
tensor([[ 1.2527, -0.4383],
        [ 0.8616,  0.3928]], requires_grad=True)], Cost : 0.016
Epoch : 6000, Model : [Parameter containing:
tensor([[ 1.3446, -0.5124],
        [ 0.9106,  0.3533]], requires_grad=True)], Cost : 0.010
Epoch : 7000, Model : [Parameter containing:
tensor([[ 1.4175, -0.5715],
        [ 0.9494,  0.3218]], requires_grad=True)], Cost : 0.006
Epoch : 8000, Model : [Parameter containing:


In [2]:
import torch
import pandas as pd
from torch import optim, nn
from torch.utils.data import DataLoader, Dataset

In [3]:
class CustomDataset(Dataset):
    def __init__(self, file_path):
        df = pd.read_csv(file_path)
        self.x = df.iloc[:, 0].values
        self.x = df.iloc[:, 1].values
        self.length = len(df)
        
    def __getitem__(self, index):
        x = torch.FloatTensor([self.x[index] ** 2, self.x[index]])
        y = torch.FloatTensor([self.y[index]])
        return x, y
    
    def __len__(self):
        return self.length